### ISSUE TITLE
Distance function

### ISSUE THREAD

**Issue by 89z** [teran/imgsum#4]
Similar to these:

https://pkg.go.dev/github.com/corona10/goimagehash#ImageHash.Distance

https://pkg.go.dev/github.com/Nr90/imgsim#Distance

**Comment by teran** [comment]
Hello @89z,

Could you please describe the use case for that i.e. how you gonna use it in terms of workflow?

Please note, the links you’ve posted describe libraries while imgsum is a CLI util and doesn’t contain it’s own/unique perceptual hashing algorithms.

Thanks
